# Generated by Django 3.0.4 on 2020-11-26 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201125_2318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='location',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
