# Generated by Django 3.1.3 on 2020-11-26 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201125_2323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='original_title',
        ),
        migrations.RemoveField(
            model_name='film',
            name='original_title_romanised',
        ),
        migrations.RemoveField(
            model_name='film',
            name='producer',
        ),
    ]
