# Generated by Django 3.1.3 on 2020-11-26 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20201125_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='api.species'),
        ),
        migrations.AlterField(
            model_name='film',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
